---

- name: install redis
  apt: 
    name: "{{ item }}" 
    state: present
  with_items:
    - redis-server
    - redis-tools

- name: configure redis servers
  include: tasks/server.yml
  with_items: "{{ redis_servers|default([]) }}"
  loop_control:
    loop_var: "redis"