---

- name: check if munin installation
  stat:
    path: /usr/share/munin/plugins/
  register: munin_installed
  tags: munin

- import_tasks: tasks/mysql-server.yml
- import_tasks: tasks/munin.yml
  when: munin_installed.stat.exists == True
  tags: munin
- import_tasks: tasks/backups.yml
  tags: mysql-backup
  
- name: logrotate for error log
  template: dest=/etc/logrotate.d/mysql-error-log src=templates/logrotate.j2
  tags: mysql-config
