---

mysql_version: "5.7"

mysql_backup:
  user: mysql-backup
  dir: /home/mysql-backup/backups
  log: /var/log/mysql-backup/backup.log
  
mysql_cnf:
  sql_mode                       : "STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER"
  bind_address                   : "{{ ansible_host }}"
  max_connect_errors             : 1000000
  key_buffer_size                : "32M"
  max_allowed_packet             : "32M"
  expire_logs_days               : 1
  innodb_flush_method            : "O_DIRECT"
  innodb_log_files_in_group      : 2
  innodb_log_file_size           : "256M"
  innodb_flush_log_at_trx_commit : 1
  innodb_file_per_table          : 1
  innodb_buffer_pool_size        : "128M"
  tmp_table_size                 : "8M"
  max_heap_table_size            : "8M"
  max_connections                : 50
  thread_cache_size              : 5
  open_files_limit               : 65535
  table_definition_cache         : 128
  table_open_cache               : 128