---

- name: requirements
  apt: name=apt-transport-https state=present

- name: deploy sury sources.list
  template: dest=/etc/apt/sources.list.d/sury.org.list src=apt.sury.org.list.j2

- name: install keys
  apt_key: url={{ item }} state=present
  with_items:
    - "https://packages.sury.org/php/apt.gpg"

- name: apt update
  apt: update_cache=yes

- name: install requirements
  environment:
      DEBIAN_FRONTEND: noninteractive
  apt: name={{ item }} state=present
  with_items:
    - libapache2-mod-php5.6
    - php5.6
    - php5.6-curl
    - php5.6-mysql
    - php5.6-readline
    - php5.6-imap
    - php5.6-mcrypt
    - php5.6-json
    - php5.6-xml
  notify:
    - restart apache