---

# Source https://decatec.de/linux/linux-einfach-e-mails-versenden-mit-msmtp/

- name: uninstall ssmtp
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - "ssmtp"

- name: install msmtp
  environment:
    DEBIAN_FRONTEND: noninteractive
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "msmtp"
    - "msmtp-mta"
    - "mailutils"

- name: msmtp conf file
  template: 
    src: "templates/msmtprc.j2" 
    dest: "/etc/msmtprc" 
    backup: "yes"
    owner: "root" 
    group: "root" 
    mode: "0644"

- name: /etc/aliases
  template:
     src: "templates/aliases.j2"
     dest: "/etc/aliases"     
     owner: "root"
     group: "root"
     mode: "0644"
     
- name: mail.rc
  lineinfile:
    path: /etc/mail.rc
    line: "set sendmail=/usr/bin/msmtp -t"
    regexp: "^set sendmail="
    create: "yes"
    owner: "root"
    group: "root"
    mode: "0644"
