---

- name: install requirements
  environment:
      DEBIAN_FRONTEND: noninteractive
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - apache2
    - openssl
    - ca-certificates

- name: deploy mpm conf
  template: 
    src: "mpm_{{ mpm.module }}.conf.j2" 
    dest: "/etc/apache2/mods-available/mpm_{{ mpm.module }}.conf"
  tags: webserver-mpm-config

- name: unlink all other mpm modules
  file: 
    path: "/etc/apache2/mods-enabled/mpm_{{ item[0] }}.{{ item[1] }}" 
    state: "absent"
  with_nested:
    - ["event","worker","prefork"]
    - ["conf","load"]
  when: (mpm.module != item[0])
  notify:
    - restart apache
  tags: webserver-mpm-config

- name: link preferred mpm module
  file: 
    src: "/etc/apache2/mods-available/{{ item }}"
    dest: "/etc/apache2/mods-enabled/{{ item }}"
    state: link
  with_items:
    - "mpm_{{ mpm.module }}.conf"
    - "mpm_{{ mpm.module }}.load"
  notify:
    - restart apache
  tags: webserver-mpm-config

- name: install precompiled mod_rpaf 0.8.4 from https://github.com/gnif/mod_rpaf
  copy:
    src: files/mod_rpaf.so
    dest: /usr/lib/apache2/modules/mod_rpaf.so
    owner: root
    group: root
    mode: 0644
  when: reverse_proxied is defined and reverse_proxied==True

- name: rpaf configs
  template: 
    src: "templates/rpaf.{{ item }}.j2" 
    dest: "/etc/apache2/mods-available/mod_rpaf.{{ item }}"
  with_items:
    - "load"
    - "conf"
  when: reverse_proxied is defined and reverse_proxied==True
  notify:
    - restart apache

- name: enable module rpaf
  file: 
    src: "/etc/apache2/mods-available/mod_rpaf.{{ item }}" 
    dest: "/etc/apache2/mods-enabled/mod_rpaf.{{ item }}" 
    state: "link"
  with_items:
    - "load"
    - "conf"
  when: reverse_proxied is defined and reverse_proxied==True
  notify:
    - restart apache

- name: apache modules
  apache2_module: 
    state: present
    name: "{{ item }}"
  with_items:
    - headers
    - rewrite
    - expires
    - ssl
  notify:
    - restart apache

- name: harden ssl
  lineinfile:
    path: /etc/apache2/mods-enabled/ssl.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  with_items:
    - regexp: ^[\s]*#?[\s]*SSLHonorCipherOrder
      line: SSLHonorCipherOrder On
    - regexp: ^[\s]*#?[\s]*SSLCipherSuite
      line: SSLCipherSuite TLSv1.3:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384
    - regexp: ^[\s]*#?[\s]*SSLCompression
      line: SSLCompression off
    - regexp: ^[\s]*#?[\s]*SSLProtocol
      line: SSLProtocol +all -SSLv3 -TLSv1 -TLSv1.1
  notify:
    - restart apache

- name: enable apache
  service:
   name: apache2
   enabled: yes